/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenuesIndexRouteImport } from './routes/venues/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as VenuesNewRouteImport } from './routes/venues/new'
import { Route as LogsNewRouteImport } from './routes/logs/new'
import { Route as VenuesVenueIdIndexRouteImport } from './routes/venues/$venueId/index'
import { Route as LogsLogIdIndexRouteImport } from './routes/logs/$logId/index'
import { Route as KnowledgeCategoryIndexRouteImport } from './routes/knowledge/$category/index'
import { Route as VenuesVenueIdEditRouteImport } from './routes/venues/$venueId/edit'
import { Route as LogsLogIdEditRouteImport } from './routes/logs/$logId/edit'
import { Route as KnowledgeCategoryItemIdRouteImport } from './routes/knowledge/$category/$itemId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesNewRoute = VenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsNewRoute = LogsNewRouteImport.update({
  id: '/logs/new',
  path: '/logs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdIndexRoute = VenuesVenueIdIndexRouteImport.update({
  id: '/venues/$venueId/',
  path: '/venues/$venueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdIndexRoute = LogsLogIdIndexRouteImport.update({
  id: '/logs/$logId/',
  path: '/logs/$logId/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCategoryIndexRoute = KnowledgeCategoryIndexRouteImport.update({
  id: '/knowledge/$category/',
  path: '/knowledge/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdEditRoute = VenuesVenueIdEditRouteImport.update({
  id: '/venues/$venueId/edit',
  path: '/venues/$venueId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsLogIdEditRoute = LogsLogIdEditRouteImport.update({
  id: '/logs/$logId/edit',
  path: '/logs/$logId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCategoryItemIdRoute = KnowledgeCategoryItemIdRouteImport.update({
  id: '/knowledge/$category/$itemId',
  path: '/knowledge/$category/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/logs/new': typeof LogsNewRoute
  '/venues/new': typeof VenuesNewRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/knowledge/$category/$itemId': typeof KnowledgeCategoryItemIdRoute
  '/logs/$logId/edit': typeof LogsLogIdEditRoute
  '/venues/$venueId/edit': typeof VenuesVenueIdEditRoute
  '/knowledge/$category/': typeof KnowledgeCategoryIndexRoute
  '/logs/$logId/': typeof LogsLogIdIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/logs/new': typeof LogsNewRoute
  '/venues/new': typeof VenuesNewRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/logs': typeof LogsIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/knowledge/$category/$itemId': typeof KnowledgeCategoryItemIdRoute
  '/logs/$logId/edit': typeof LogsLogIdEditRoute
  '/venues/$venueId/edit': typeof VenuesVenueIdEditRoute
  '/knowledge/$category': typeof KnowledgeCategoryIndexRoute
  '/logs/$logId': typeof LogsLogIdIndexRoute
  '/venues/$venueId': typeof VenuesVenueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/logs/new': typeof LogsNewRoute
  '/venues/new': typeof VenuesNewRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/knowledge/$category/$itemId': typeof KnowledgeCategoryItemIdRoute
  '/logs/$logId/edit': typeof LogsLogIdEditRoute
  '/venues/$venueId/edit': typeof VenuesVenueIdEditRoute
  '/knowledge/$category/': typeof KnowledgeCategoryIndexRoute
  '/logs/$logId/': typeof LogsLogIdIndexRoute
  '/venues/$venueId/': typeof VenuesVenueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/logs/new'
    | '/venues/new'
    | '/knowledge/'
    | '/logs/'
    | '/venues/'
    | '/knowledge/$category/$itemId'
    | '/logs/$logId/edit'
    | '/venues/$venueId/edit'
    | '/knowledge/$category/'
    | '/logs/$logId/'
    | '/venues/$venueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/logs/new'
    | '/venues/new'
    | '/knowledge'
    | '/logs'
    | '/venues'
    | '/knowledge/$category/$itemId'
    | '/logs/$logId/edit'
    | '/venues/$venueId/edit'
    | '/knowledge/$category'
    | '/logs/$logId'
    | '/venues/$venueId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/logs/new'
    | '/venues/new'
    | '/knowledge/'
    | '/logs/'
    | '/venues/'
    | '/knowledge/$category/$itemId'
    | '/logs/$logId/edit'
    | '/venues/$venueId/edit'
    | '/knowledge/$category/'
    | '/logs/$logId/'
    | '/venues/$venueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LogsNewRoute: typeof LogsNewRoute
  VenuesNewRoute: typeof VenuesNewRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  KnowledgeCategoryItemIdRoute: typeof KnowledgeCategoryItemIdRoute
  LogsLogIdEditRoute: typeof LogsLogIdEditRoute
  VenuesVenueIdEditRoute: typeof VenuesVenueIdEditRoute
  KnowledgeCategoryIndexRoute: typeof KnowledgeCategoryIndexRoute
  LogsLogIdIndexRoute: typeof LogsLogIdIndexRoute
  VenuesVenueIdIndexRoute: typeof VenuesVenueIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/new': {
      id: '/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof VenuesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/new': {
      id: '/logs/new'
      path: '/logs/new'
      fullPath: '/logs/new'
      preLoaderRoute: typeof LogsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId/': {
      id: '/venues/$venueId/'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId/'
      preLoaderRoute: typeof VenuesVenueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId/': {
      id: '/logs/$logId/'
      path: '/logs/$logId'
      fullPath: '/logs/$logId/'
      preLoaderRoute: typeof LogsLogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$category/': {
      id: '/knowledge/$category/'
      path: '/knowledge/$category'
      fullPath: '/knowledge/$category/'
      preLoaderRoute: typeof KnowledgeCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$venueId/edit': {
      id: '/venues/$venueId/edit'
      path: '/venues/$venueId/edit'
      fullPath: '/venues/$venueId/edit'
      preLoaderRoute: typeof VenuesVenueIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$logId/edit': {
      id: '/logs/$logId/edit'
      path: '/logs/$logId/edit'
      fullPath: '/logs/$logId/edit'
      preLoaderRoute: typeof LogsLogIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$category/$itemId': {
      id: '/knowledge/$category/$itemId'
      path: '/knowledge/$category/$itemId'
      fullPath: '/knowledge/$category/$itemId'
      preLoaderRoute: typeof KnowledgeCategoryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LogsNewRoute: LogsNewRoute,
  VenuesNewRoute: VenuesNewRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  KnowledgeCategoryItemIdRoute: KnowledgeCategoryItemIdRoute,
  LogsLogIdEditRoute: LogsLogIdEditRoute,
  VenuesVenueIdEditRoute: VenuesVenueIdEditRoute,
  KnowledgeCategoryIndexRoute: KnowledgeCategoryIndexRoute,
  LogsLogIdIndexRoute: LogsLogIdIndexRoute,
  VenuesVenueIdIndexRoute: VenuesVenueIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
